# `NumPy`: Numerical operations in Python

This tutorial uses material also found in the [SciPy 1.0 Nature Methods](https://www.nature.com/articles/s41592-019-0686-2) and [NumPy Array IEEE](10.1109/MCSE.2011.37) article and at [https://numpy.org/](https://numpy.org/).

### Learning outcomes:
 - Understand Python Library `NumPy`
 - Use `numpy arrays`
 - Apply loops and logical operators on `numpy arrays`

Data scientists spend a lot of time – wait for it – working with ***data***! To work with **data** it is critical to organize the data in a way that facilitate the work on the potential analyses we might need to do. So organizing data means guessing what type of work we will want to do with the dataset. And, odd is it may seem, good guessing requires some practice. The data organization process will require: 

* store the data a clear and systematic way
* provide methods to access the data that are simple and straightforward
* be flexible enough so to and allow to modify the format of the data for various needs

NumPy is the fundamental `library` for mathematical operations and computations in Python. 

The NumPy library provides a series of objects that can be used to store data (represent the numbers in a dataset for Python) and a series of methods to analyze data (provide operations that can compute, say the mean or the standard deviation of some numbers in a dataset).

The NumPy `array` is the workhorse of NumPy and we will spend quite some time with it below. The numpy array is a multidimensional array object, that means that it 
  - (1) is an object for programming (so it has methods and proprties of an object, just like you cup holds coffee and has colors, 
  - (2) the Numpy array can hold data and have a bunch of properties that we can look as we look at the colors on the cup. The properties of the array help us recognize and understand what is in the array and sometimes that is really important, for example, you would not want to drink from someone else's cup, would you?

A variety of fast numerical operations on arrays are provided by NumPy. These include operations that are mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 

NumPy is the base of scientific computing and data science libraries such as [Pandas](https://pandas.pydata.org/) [scipy.org](https://scipy.org/), and [scikit-learn.org](https://scikit-learn.org/) among many others.

In other (simpler?) words, Numpy arrays are grids or tables for holding, accessing, and manipulating data. They are created and accessed in ways that are very similar to the ways Python `lists` can be accessed.

So what we are going to do is to recall how `lists` work (lists are handy!), then we will graduate to `numpy arrays` and see what they can do. 

### Python lists

We have covered Python `lists` (and other datatypes) in previous tutorials. Python `lists` (a list of things) is build by collecting, ahem, a list of things using `[square brackets]`.

For example:

In [1]:
mylist = ['this', 3, 'list', 4+2j, 6.66]

We can address elements in a list by using indices and the `:` (colon) operator.

In [2]:
mylist[0:3]

['this', 3, 'list']

We can read this as "Give me all the elements in the interval between 0 **inclusive** to 3 **exclusive**."

I know this is weird. But at least for any two indexes `a` and `b`, the number of elements you get back from `mylist[a,b]` is always equal to `b` minus `a`, so I guess that's good!

We can get any consecutive hunk of elements using `:`.

In [3]:
mylist[2:5]

['list', (4+2j), 6.66]

If you omit the indexes, Python will assume you want everything.

In [4]:
mylist[:]

['this', 3, 'list', (4+2j), 6.66]

List can obviously host also homogeneous types of data, such as `int` or `float`:

In [6]:
mylistHomogeneous = [2, 3.14, 10.5, 11.13, 12.7, 4.31]

### Numpy Arrays

Numpy arrays were designed to be lists with superpowers, so almost everything we learned about  `lists` will apply to `numpy arrays` as well! The one big difference is that all elements of a `numpy array` must be of the same data type. This allows calculations on `numpy arrays` to be much faster than they would be on `lists`.

A NumPy array is a multidimensional, uniform collection of elements (that is, all elements occupy the same number of bytes in memory). An array is characterized by
 - the type of elements it contains and
 - its shape. 
 
For example, a matrix might be represented as an array of shape M×N that contains numbers, such as floating-point or complex numbers. Unlike matrices, NumPy arrays can have up to 32 dimensions; they might also contain other kinds of elements (or even combinations of elements), such as Booleans or dates. [Ref. Van Der Walt et al. IEEE](10.1109/MCSE.2011.37)

Not to state the obvious, but to use `numpy arrays`, we'll need to `import` the library `numpy`. The standard is to import `numpy` as `np`:

In [7]:
import numpy as np

`arrays` can be made by simply asking for one and filling it out with values, in much the same way we make a `list`.

In [8]:
myarr = np.array([2, 4, 6, 8, 9, 10])

The command `print` can be used also on `NumPy arrays` and it returns the content of the array:

In [9]:
print(myarr)

[ 2  4  6  8  9 10]


By simply returning the array object name (`myarr`) the output is a bit more informative and it returns the type (`array`):

In [10]:
myarr

array([ 2,  4,  6,  8,  9, 10])

From then on, all the indexing we've learned so far applies directly! Square brackets are used for indexing and the same type of addressing can be used as we have learned for `lists`:

In [11]:
myarr[4]

9

In [12]:
myarr[-3:]

array([ 8,  9, 10])

$\color{blue}{\text{Complete the following exercise.}}$

  - Create a `NumPy array` containing both `int`, `float` and `complex` datatypes.

  [Use the cell below to show your code]

In [13]:
np.array([4, 3.23, 1+4j])

array([4.  +0.j, 3.23+0.j, 1.  +4.j])

  - Create a `NumPy array` containing both `str` as datatypes.

  [Use the cell below to show your code]

In [14]:
np.array(['twenty', 'forty'])

array(['twenty', 'forty'], dtype='<U6')

### Operations on `numpy arrays`: the difference between `lists` and `arrays`
Indeed, we can make an array directly out of a list.

In [16]:
myArrFromList = np.array(mylistHomogeneous)

In [17]:
myArrFromList

array([ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31])

And then of course we can index it exactly the same way, so... *Wait, why are we making arrays now? What's the difference?*

One **huge** difference is that if we wanted to do some math with basic Python lists, the fact that they can hold multiple types of data elements does not assure that the mathematical operations will perform.

In [18]:
mylist + 5

TypeError: can only concatenate list (not "int") to list

`numpy` arrays instead contain numerical elements by definition. This definition assures the ability to perform math on the arrays. So, whereas the addition above did not work when using the `list`, it does work when using the `numpy` array, even though both `list` and `array` contain the same elements!

In [19]:
myArrFromList + 5

array([ 7.  ,  8.14, 15.5 , 16.13, 17.7 ,  9.31])

Now **that** seems like it might be useful!

$\color{blue}{\text{Complete the following exercise.}}$

  - What happens when you add a number to a `NumPy array`? How do the content of the array change?

  [Use the cell below to show answer the question]

the number is added to each number in the array 

  - Create a new `array` and multiply the array by a complex number:

  [Use the cell below to show your code]

In [21]:
a= np.array([4,5,34,6,7,])
a * 4+3j

array([ 16.+3.j,  20.+3.j, 136.+3.j,  24.+3.j,  28.+3.j])

    [Use the cell below to describe in your own words what happnes to the elements of the array after multiplying for a complex number]

each number was multiplied by the integer and added the second half of the complex number 

### More operations on `arrays`

Two arrays can be added, or subtracted, or multiplied or whatever!

In [22]:
myarr + myArrFromList

array([ 4.  ,  7.14, 16.5 , 19.13, 21.7 , 14.31])

In [23]:
myarr * myArrFromList

array([  4.  ,  12.56,  63.  ,  89.04, 114.3 ,  43.1 ])

In [24]:
myarr / myArrFromList

array([1.        , 1.27388535, 0.57142857, 0.71877808, 0.70866142,
       2.32018561])

We can also **combine** our 2 arrays into a single ***two dimensional (2D) array***.

In [25]:
twoDarr = np.array([myarr, myArrFromList])

In [26]:
twoDarr

array([[ 2.  ,  4.  ,  6.  ,  8.  ,  9.  , 10.  ],
       [ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31]])

Simple though this may seem, *2D arrays just like this are the bedrock of data analysis!* Arrays of real data are usually larger – sometimes much much larger! – but all the principles are the same and all you as a Data Scientists need to remember is the dimensionality of the data arrays. Python will then compute what you ask for.

But, hold on one second. Remembering the dimensionality of the array is ** *very* ** imoortant. Indeed Python can perform some operations if two arrays do *not* have the same dimensions, but other operations are likely to fail.

For example, imagine two `arrays` with different dimensions:

In [27]:
smallArray = [2, 3, 4]
largeArray = [2, 3, 4, 5, 6, 7]

The two arrays can be added together by using the symbol `+`:

In [28]:
smallArray + largeArray

[2, 3, 4, 2, 3, 4, 5, 6, 7]

Yet, the same two arrays cannot be multiplied:

In [29]:
smallArray * largeArray

TypeError: can't multiply sequence by non-int of type 'list'

This is because Python cannot identify elements to match during the multiplication.

$\color{blue}{\text{Complete the following exercise.}}$

  - What happens when you add two arrays of different dimensions? Say one array with 6 complex numers and one with 4 `float` numbers?

      [Use the cell below to show how to create and add the two arrays]

In [30]:
a= np.array([3.4,2.3,6.7,8.6,8])
          
b= np.array([3j,9+2j,2+3j,8+5j])

a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

    [Use the cell below to describe in your own words what happens to the arrays as result of the multiplication]

cant multiply 

cant add different dimensions 

### Methods of `numpy arrays`

So the shape of the array (the dimensionality) is key, especially if we plan on doing math with the arrays, whihc is the primary goal of the arrays! 

`numpy arrays` are Python objects and as such they have `methods`. A variety of methods exist for the array and `shape` is the one that allow us to retrieve the dimensionality of an array.

In [34]:
twoDarr

array([[ 2.  ,  4.  ,  6.  ,  8.  ,  9.  , 10.  ],
       [ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31]])

In [33]:
twoDarr.shape

(2, 6)

Unlike lists, which are always just lists, arrays can come in any shape. So it's *really* convenient that they can tell us what shape they are straight away.

Indexing into 2D arrays is a straightforward extension of indexing into 1D arrays or lists. We just provide a second index after a `,` (comma). Like this.

In [35]:
twoDarr[1,3]

11.13

The first index refers to the **row index**, and the second to the **column index**. In this case, we're asking for the value in the second row and the fourth column, which is indeed 7 (remember *the first row and column are index=0!*).

We can play all the same games indexing with 2D arrays as we can with 1D arrays, we just have to remember that everything before the comma `,` refers to the *rows* in that it specifies locations along the *vertical dimension*, and everything after the comma `,` refers to the *columns* in that it specifies locations along the *horizontal dimension*.

So this:

In [36]:
twoDarr[:,0:3]

array([[ 2.  ,  4.  ,  6.  ],
       [ 2.  ,  3.14, 10.5 ]])

means "Give me all the rows (the colon `:`) in the first 3 columns (the "`0:3`)."

I told you that the colon all alone by itself would end up being useful!!! In this case for example, by using the `:` you do not need to type many indices (one per row) and you even do not need to remmeber how many rows there are, just use `:` and Python will return all the elements.

A few more examples:

In [37]:
# the last row (regardless of the number of rows, 
# again you do not need to knowhow many rows exist)
twoDarr[-1,:] 

array([ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31])

In [38]:
twoDarr[:,-2:] # last two columns

array([[ 9.  , 10.  ],
       [12.7 ,  4.31]])

In [39]:
twoDarr[0,::2] # first row, every other column

array([2., 6., 9.])

To get good at this, you don't need natural born talent or anything like that. Like so much in life, the key is *practice, practice, practice*!!! So play around! You can't break your computer or anything!

Another neat trick that arrays can do is *transpose* themselves, flipping the rows for columns.

(Hold your right hand in front of your face so that you're looking at your palm with your fingers pointing towards the left. Now flip your hand so that you're looking at the back of your hand with your fingers pointing up. You just *transposed* your hand such that the first row (your pointer finger) became the first column!)

In [40]:
colarr = twoDarr.T

In [41]:
colarr

array([[ 2.  ,  2.  ],
       [ 4.  ,  3.14],
       [ 6.  , 10.5 ],
       [ 8.  , 11.13],
       [ 9.  , 12.7 ],
       [10.  ,  4.31]])

Why would we want to do that? By convention, *variables* in datasets should correspond to the columns, and *observations* should correspond to the rows. So we have taken data in which this was not so and turned it into an array in which the columns are the first few non-prime numbers and the prime numbers, respectively, and the rows correspond to the instances in order (1st , 2nd, 3rd, ....).

So that really speeds up a common **data wrangling** operation. 

Now that we have the data into shape, we can unleash all the powers of numpy arrays, powers which pandas DataFrames will inherit and build upon!

For example, who's bigger overall, the primes or the non-primes?

In [42]:
colarr.sum(0)

array([39.  , 43.78])

The primes win! 
In `colarr.sum(0)`, the 0 means "the first (vertical) dimension", i.e., sum the values *across the rows* within each column. To sum along the second dimension, we do:

In [43]:
colarr.sum(1)

array([ 4.  ,  7.14, 16.5 , 19.13, 21.7 , 14.31])

So any numpy array knows how to add up the numbers in it by row or by column (see what happens if you leave off the dimension, like this `colarr.sum()`. The list of things that numpy arrays can do themselves is pretty impressive.

Check it out [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

(or paste this into your browser: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

$\color{blue}{\text{Complete the following exercise.}}$

  - How many methods does a numpy array have? alot 
  
  - Create a new 2-dimensional array, and show the use of two methods not used above (`prod` and `round` could be two simple ones, but no pressure):
  
  [Use the cell below to show how to create and add the two arrays]
  
*Hint:* The symbol `?` can be used at the end of a method and that can help understand how to use the method, for example, `myarray.shape?`

In [49]:
newarray = np.array([[2,3,4,5,6],[32,45,76,34,89]]) 
newarray.mean()
newarray.flatten()

array([ 2,  3,  4,  5,  6, 32, 45, 76, 34, 89])

### `NumPy` methods to create arrays

Often, we want to create a array that we know we're going to put values in later. For example, we might be planning on doing a computation that will result in 3 sets of 7 values, and we want be able to store them directly into an array. We can pre-make an array filled with zeros with `np.zeros(r, c)`.

In [50]:
myzeros = np.zeros((7, 3))

In [51]:
myzeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Another handy method to create arrays is `ones`

In [52]:
myones = np.ones((3,4))

In [53]:
myones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

We will encounter other `NumPy` methods in later tutorials. For the time being one last method that will turn out very handy when modelling data:

In [54]:
myRandomNumArray = np.random.randn(10,1)
print(myRandomNumArray)

[[ 0.36331054]
 [-0.16342211]
 [ 0.34109182]
 [-0.4856297 ]
 [ 0.94441435]
 [-0.00210383]
 [-0.33511988]
 [ 0.21489189]
 [ 1.41418467]
 [ 0.87478033]]


The `numpy` submodule `random` contains a variety of methods to create arrays containing random numbers. Generating random numbers is helpful in many applications, for example, they can be used to create normally distributed noise, or data with normally distributed noise, etc. 

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Create a new 1-dimensional array of uniformly-distributed random number:
  
  [Use the cell below to show your code]


In [61]:
randomnum= np.random.randn(8,1)
randomnum

array([[ 0.82190125],
       [-0.1196976 ],
       [-0.09093496],
       [-0.53578935],
       [-0.14761254],
       [ 0.78366598],
       [ 1.27725524],
       [ 0.68152757]])

  
  - Create a new  2-dimensional array of normally-distributed random number:
  
  [Use the cell below to show your code]


In [57]:
randomnum= np.random.randn(2,8)
randomnum

array([[ 0.44875333,  0.91113699,  0.03084624, -1.09485482,  1.08723213,
        -0.86716887, -0.50266488,  0.90623919],
       [ 0.33059815,  0.02476138, -0.60439458, -0.13970042, -0.08428672,
        -0.4080155 ,  0.52939485,  0.5746177 ]])

Let's now create a simple 1-D array and explore what happens when we add a number to the values and what happens when we multiply the numbers in the array:

In [58]:
size  = 20
origArray = np.random.randn(size,1)

Let's look at the values in the array.

In [59]:
print(origArray)

[[-0.59740192]
 [-0.06976521]
 [-1.54304853]
 [-0.85749585]
 [-1.79578567]
 [-0.6953804 ]
 [-0.21944894]
 [-2.24942596]
 [ 0.13409998]
 [-0.71686598]
 [ 0.00237846]
 [ 0.0319154 ]
 [ 0.25654441]
 [ 0.21658811]
 [-0.17908907]
 [ 1.41702842]
 [-0.31419145]
 [-0.82688725]
 [-0.26846612]
 [-0.0248647 ]]


There seem to be a variety of numbers, some positive, some negative, as expected because `randn` is supposed to generate numbers centered at 0 (i.e., with mean 0) and standard deviation of 1.

Let's compute the standard deviation and mean of these numbers. Numpy provides to handy methods:

In [60]:
mean = np.mean(origArray)
sd = np.std(origArray)

print(['The mean is:', mean])
print(['the STD is:', sd])

['The mean is:', -0.4149781127249792]
['the STD is:', 0.7871218260034775]


Well, okay, the mean is not quite close to 0, but perhaps close enough? The standard deviation seems pretty close to the expected value of 1.

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Create a new 1-dimensional array of 100 normally-distributed random numbers:
  
  [Use the cell below to show your code]


In [63]:
size = 100
onedimarray= np.random.randn(size, 1)
onedimarray

array([[-1.88804413],
       [ 0.49901758],
       [ 1.46799614],
       [ 1.49339622],
       [-0.6715107 ],
       [ 0.18440528],
       [-0.99322521],
       [-0.9107164 ],
       [-0.33082295],
       [-1.05545184],
       [ 0.07140696],
       [-0.46245308],
       [-0.71660869],
       [ 0.45888253],
       [ 0.10807264],
       [ 0.22930737],
       [-3.43851054],
       [-1.1108    ],
       [-0.22678909],
       [-0.61436177],
       [-0.14523808],
       [ 0.79291047],
       [-0.03475636],
       [-0.06866811],
       [ 1.20021832],
       [-0.88662929],
       [ 0.03460073],
       [-0.9514938 ],
       [-1.14677166],
       [ 1.04271544],
       [-1.19041642],
       [ 1.02924374],
       [-0.44056763],
       [-0.91498363],
       [-0.03293362],
       [ 0.67813518],
       [ 1.75367677],
       [-0.74227155],
       [-0.92561658],
       [-0.0934978 ],
       [ 0.68808078],
       [ 0.67038301],
       [ 0.87618184],
       [-1.22851396],
       [-0.54646238],
       [-0

   - What happens to the mean and standard deviation after increasing the size of the array? Are they closer of further from the expected values? Why? 
        
  [Use the cell below to show your code]


In [65]:
onedimarray.mean()
onedimarray.std()

0.9925372653855783

What happens if we add 5 to the array?

In [74]:
x  = 5 + origArray

In [67]:
print(x)

[[4.40259808]
 [4.93023479]
 [3.45695147]
 [4.14250415]
 [3.20421433]
 [4.3046196 ]
 [4.78055106]
 [2.75057404]
 [5.13409998]
 [4.28313402]
 [5.00237846]
 [5.0319154 ]
 [5.25654441]
 [5.21658811]
 [4.82091093]
 [6.41702842]
 [4.68580855]
 [4.17311275]
 [4.73153388]
 [4.9751353 ]]


It looks like the values shifted. But how much? It looks like they recentered at 5, the value we added. So we can perhaps assume that now the distribution of numbers is normally distributed but with a mean of 5. The standard deviation has not bee changed. It is still at 1, trust me for the moment and let try multiplying the numbers.

In [75]:
x  = 2 * origArray
print(x)

[[-1.19480384]
 [-0.13953041]
 [-3.08609705]
 [-1.7149917 ]
 [-3.59157135]
 [-1.39076081]
 [-0.43889787]
 [-4.49885192]
 [ 0.26819997]
 [-1.43373195]
 [ 0.00475692]
 [ 0.0638308 ]
 [ 0.51308883]
 [ 0.43317622]
 [-0.35817814]
 [ 2.83405684]
 [-0.6283829 ]
 [-1.65377449]
 [-0.53693224]
 [-0.0497294 ]]


It looks like the values increased. There seem to be a larger variality, more bigger numbers, both negative and positive. So perhaps the STD is not at 1 anymore. Could it be at 2?

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Compute the mean, std and median of `x`:
  
  [Use the cell below to show your code]


In [69]:
x.mean()

-0.8299562254499584

In [70]:
x.std()

1.574243652006955

In [73]:
median(x)

NameError: name 'median' is not defined

  
  - What are the mean, std and median of `x`? Why, what is going on here?
  
  [Use the cell below to show answer in your own words]

### Summary

So in this tutorial we have shown how to organize and manipulate data using Python `numpy` `arrays`.

So those are the basics of numpy arrays. They:

* store values in rows and columns
* each dimension starts at index zero (like lists)
* can be accessed using
    - square brackets `[]` with row and column indexes separated by a comma
    - integer indexes (including negative "start from the end" indexes)
    - a colon `:` (or two if you want a step value other than 1)
* can have maths done to every element in one go
* can be added, subtracted, etc. from one another
* have superpowers! they can compute stuff along their rows and columns!

The operations that are available for these two data types will be the base for many things that you might need to do as a Data Scientist. 

`Numpy arrays` Can host a variety of data types. Although this might be too much for now, below a table of all the data types an `array` can support:

| Type	| Description |
| --- | --- |
| bool |	Boolean (True or False) stored as a bit (0, 1) |
| inti	| Platform integer (normally either int32 or int64) |
| int8	| Byte (-128 to 127) |
| int16	| Integer (-32768 to 32767) |
| int32	| Integer (-2 ** 31 to 2 ** 31 -1) |
| int64	| Integer (-2 ** 63 to 2 ** 63 -1) |
| uint8	| Unsigned integer (0 to 255) |
| uint16	| Unsigned integer (0 to 65535) |
| uint32	| Unsigned integer (0 to 2 ** 32 – 1) |
| uint64	| Unsigned integer (0 to 2 ** 64 – 1) |
| float16	| Half precision float: sign bit, 5 bits exponent, and 10 bits mantissa |
| float32	| Single precision float: sign bit, 8 bits exponent, and 23 bits mantissa |
| float64 or float	| Double precision float: sign bit, 11 bits exponent, and 52 bits mantissa |
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 or complex	| Complex number, represented by two 64-bit floats (real and imaginary components) |

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Generate an 1-D array of mean = 10 and std = 1.5:
  
  [Use the cell below to show your code]

In [21]:
import numpy as np
test= 10 + 1.5*np.random.randn(100000,1)

In [22]:
test.mean()

9.994049683202082

In [23]:
test.std()

1.4977088180908105